# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_model_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my_model_api.proto',
  package='mymodelapi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12my_model_api.proto\x12\nmymodelapi\"$\n\x0cMyModelInput\x12\t\n\x01x\x18\x01 \x03(\x05\x12\t\n\x01y\x18\x02 \x03(\x05\",\n\rMyModelOutput\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x03(\x05\x32N\n\nMyModelApi\x12@\n\x07Predict\x12\x18.mymodelapi.MyModelInput\x1a\x19.mymodelapi.MyModelOutput\"\x00\x62\x06proto3'
)




_MYMODELINPUT = _descriptor.Descriptor(
  name='MyModelInput',
  full_name='mymodelapi.MyModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mymodelapi.MyModelInput.x', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='mymodelapi.MyModelInput.y', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=70,
)


_MYMODELOUTPUT = _descriptor.Descriptor(
  name='MyModelOutput',
  full_name='mymodelapi.MyModelOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='mymodelapi.MyModelOutput.model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='mymodelapi.MyModelOutput.y', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['MyModelInput'] = _MYMODELINPUT
DESCRIPTOR.message_types_by_name['MyModelOutput'] = _MYMODELOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyModelInput = _reflection.GeneratedProtocolMessageType('MyModelInput', (_message.Message,), {
  'DESCRIPTOR' : _MYMODELINPUT,
  '__module__' : 'my_model_api_pb2'
  # @@protoc_insertion_point(class_scope:mymodelapi.MyModelInput)
  })
_sym_db.RegisterMessage(MyModelInput)

MyModelOutput = _reflection.GeneratedProtocolMessageType('MyModelOutput', (_message.Message,), {
  'DESCRIPTOR' : _MYMODELOUTPUT,
  '__module__' : 'my_model_api_pb2'
  # @@protoc_insertion_point(class_scope:mymodelapi.MyModelOutput)
  })
_sym_db.RegisterMessage(MyModelOutput)



_MYMODELAPI = _descriptor.ServiceDescriptor(
  name='MyModelApi',
  full_name='mymodelapi.MyModelApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='mymodelapi.MyModelApi.Predict',
    index=0,
    containing_service=None,
    input_type=_MYMODELINPUT,
    output_type=_MYMODELOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYMODELAPI)

DESCRIPTOR.services_by_name['MyModelApi'] = _MYMODELAPI

# @@protoc_insertion_point(module_scope)
