# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import my_model_api_pb2 as my__model__api__pb2


class MyModelApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/mymodelapi.MyModelApi/Predict',
                request_serializer=my__model__api__pb2.MyModelInput.SerializeToString,
                response_deserializer=my__model__api__pb2.MyModelOutput.FromString,
                )


class MyModelApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Get predictions from model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyModelApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=my__model__api__pb2.MyModelInput.FromString,
                    response_serializer=my__model__api__pb2.MyModelOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mymodelapi.MyModelApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyModelApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mymodelapi.MyModelApi/Predict',
            my__model__api__pb2.MyModelInput.SerializeToString,
            my__model__api__pb2.MyModelOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
